### ISSUE TITLE
since 2.0.19 now rendering empty hreflang tags for missing locales

### ISSUE THREAD

**Issue by Grisgruis** [justkidding96/statamic-aardvark-seo#107]
On our multilanguage site, we have blog items which are missing in some locales, but since 2.0.19 an empty hreflang gets rendered for the missing locales. 

I think there is a null filter missing in the 2.0.19 version:

https://github.com/WithCandour/statamic-aardvark-seo/compare/2.0.18...2.0.19

**Comment by LorensoD** [comment]
I'm also experiencing this issue since 2.0.19.

**Comment by AndrewHaine** [comment]
Thanks both for flagging. This has been fixed in 2.0.21 :)
