### ISSUE TITLE
Multisite entries with no-index in sitemap.xml

### ISSUE THREAD

**Issue by GertTimmerman** [justkidding96/statamic-aardvark-seo#112]
I have multiple entries where i have set index to no-index. For these entries i have created versions for other sites. These translated versions have the no-index inherited from the origin. But these translated versions are incorrectly included in the sitemap.xml

**Comment by AndrewHaine** [comment]
Thanks for reporting @GertTimmerman ,

This has been fixed in 2.0.22 :)
