### ISSUE TITLE
Sitemap namespace not declared correctly

### ISSUE THREAD

**Issue by AndrewHaine** [justkidding96/statamic-aardvark-seo#113]
Users are receiving notifications via GSC that their sitemap namespace is not declared, specifically in the sitemap index

**Comment by AdD959** [comment]
this may be a separate issue but we're also having problems with sitemap erroring in production due to it being rendered in http rather than https. Setting the APP_URL to https does not help, nor does enforcing https in the AppServiceProvider.

**Comment by AdD959** [comment]
Looking into this further, I've found that the addon serves via http on servers behind load balancers. Are you able to add some configuration that forces sitemap.xml to serve https? At the moment it is only the aardvark seo tools which are being served in http

**Comment by AndrewHaine** [comment]
Hi @AdD959 ,

I'm going to close this off as I've fixed the original problem but will open a new issue with your comments above as I believe this is a different issue.
