### ISSUE TITLE
Feature to bulk upload redirects as CSV

### ISSUE THREAD

**Issue by mattmultiplied** [justkidding96/statamic-aardvark-seo#115]
No bug, just a potential feature, would be great if there was the ability to upload a CSV of redirects with the column headings 'source_url', 'target_url', 'status' and 'is_active'.

Would be great when migrating a website from a different CMS such as Wordpress over to Statamic.

**Comment by AndrewHaine** [comment]
Thanks @mattmultiplied ,

I'm closing this as a duplicate of https://github.com/WithCandour/statamic-aardvark-seo/issues/47 but this is on our list to look into.

Thanks,
Andrew
