### ISSUE TITLE
Redirects for existing pages

### ISSUE THREAD

**Issue by dave-smyth** [justkidding96/statamic-aardvark-seo#128]
If we create a redirect for a page that exists the redirect doesn’t work. I guess this is the default and expected behaviour to prevent accidental redirects.

Is that interpretation correct? Do entries need to be unpublished (or deleted) for the redirect to work?

**Comment by AndrewHaine** [comment]
Hi @websmyth ,

That's correct, the current behaviour is to only redirect if the request would have resulted in a 404 so unpublishing or deleting and entry will result in the redirect working.

If you need a redirect to override a page i'd suggest redirecting at the server-level e.g. via htaccess.

Thanks,
Andrew

**Comment by dave-smyth** [comment]
Makes sense – cheers. 🙌
