### ISSUE TITLE
Antlers tags in Content Defaults

### ISSUE THREAD

**Issue by dave-smyth** [justkidding96/statamic-aardvark-seo#129]
From [issue #98](https://github.com/WithCandour/statamic-aardvark-seo/issues/98), it seems that it should be possible to add antlers tags in `Content Defaults > [collection name] Defaults > Meta Description`, but struggling to get that to work here.

I have a Bard field called `short_description` – I’ve tried adding that to the Meta Description as both:
- `{{ short_description }}`
- `{{ short_description | strip_tags }}`

Neither seem to be pulled through to the `og:description` property.

I’ve tried this on existing and new entries with no luck so far. Perhaps I’m missing something?

**Environment**
Statamic 3.3.9 Pro
Laravel 8.83.9
PHP 7.4.27
withcandour/aardvark-seo 2.0.24

**Comment by dave-smyth** [comment]
Following up on this – is this something that should be possible and I need to experiment with it further or a bug/feature request?

**Comment by AndrewHaine** [comment]
Hi @websmyth ,

Apologies for the delay, i'll schedule in some time to look into this this week. The `antlers` setting is set to `true` in the blueprint so this should work in theory.

Please could you let me know which antlers parser you are using with Statamic 3.3 are you on the old regex one or the new runtime parser?

Thanks,
Andrew

**Comment by AndrewHaine** [comment]
Hi @websmyth ,

I believe this was an issue with Aardvark following the Statamic 3.3 upgrade, we've identified the fix and it will be released in Aardvark v2.0.25.

**Comment by dave-smyth** [comment]
Perfect, thanks – I’ll take a another look when 2.0.25 is out. 🙌

**Comment by dave-smyth** [comment]
This worked – cheers! 👏
