### ISSUE TITLE
If both social media link fields saved as blank - throws error

### ISSUE THREAD

**Issue by kristiana-s** [justkidding96/statamic-aardvark-seo#130]
Errors in log
` Undefined array key \"url\" at /.../withcandour/aardvark-seo/src/Schema/Parts/SiteOwner.php:49)`

and 
 
 `(Facade\\Ignition\\Exceptions\\ViewException(code: 0): Undefined array key \"url\" at /.../vendor/withcandour/aardvark-seo/src/../resources/views/tags/head.antlers.html:0)`

**Comment by AndrewHaine** [comment]
Fixed in 2.0.25 :)
