### ISSUE TITLE
AardvarkSeoTags methods body and footer not returning 

### ISSUE THREAD

**Issue by oscarlundberg-sthlm** [justkidding96/statamic-aardvark-seo#147]
$view is returned empty if the Statamic version isn't regex.

(Sorry for the bad markdown formatting)

Currently:

`    /**
     * Return the body content
     */
    public function body()
    {
        $data = PageDataParser::getData(collect($this->context));

        if (config('statamic.antlers.version') == 'regex') {
            $view = view('aardvark-seo::tags.body', $data);
        } else {
            View::make('aardvark-seo::tags.body', $data->all());
        }

        return $view;
    }

    /**
     * Return the footer content
     */
    public function footer()
    {
        $data = PageDataParser::getData(collect($this->context));

        if (config('statamic.antlers.version') == 'regex') {
            $view = view('aardvark-seo::tags.footer', $data);
        } else {
            View::make('aardvark-seo::tags.footer', $data->all());
        }

        return $view;
    }`

Suggestion:

`    /**
     * Return the body content
     */
    public function body()
    {
        $data = PageDataParser::getData(collect($this->context));

        if (config('statamic.antlers.version') == 'regex') {
            $view = view('aardvark-seo::tags.body', $data);
        } else {
            $view = View::make('aardvark-seo::tags.body', $data->all());
        }

        return $view;
    }

    /**
     * Return the footer content
     */
    public function footer()
    {
        $data = PageDataParser::getData(collect($this->context));

        if (config('statamic.antlers.version') == 'regex') {
            $view = view('aardvark-seo::tags.footer', $data);
        } else {
            $view = View::make('aardvark-seo::tags.footer', $data->all());
        }

        return $view;
    }`

**Comment by AndrewHaine** [comment]
Thanks @oscarlundberg-sthlm , This has been fixed in 2.0.30
