### ISSUE TITLE
Sitemap Controller throwing faulty 404's

### ISSUE THREAD

**Issue by kevinmeijer97** [justkidding96/statamic-aardvark-seo#154]
`vendor/withcandour/aardvark-seo/src/Http/Controllers/Web/SitemapController.php`
In the above controller there are a few lines using `abort(404)` to throw the 404 page.
This breaks your site when using blade because this doesn't load in the default variables that Statamic loads.
The solution would be to use `use Statamic\Exceptions\NotFoundHttpException;` and instead of the abort you would throw the NotFoundHttpException like `throw new NotFoundHttpException;`.

<img width="619" alt="Screenshot 2023-01-31 at 16 56 51" src="https://user-images.githubusercontent.com/9716909/215811502-8841e91c-dd6d-41d7-8ed4-961206b94347.png">

**Comment by ols-bradshaw** [comment]
Hi there. Thank you for flagging this.

The fix for this will be included in the upcoming `2.0.31` release
