### ISSUE TITLE
Statamic 4 Compatibility 

### ISSUE THREAD

**Issue by duncanmcclean** [justkidding96/statamic-aardvark-seo#159]
Hello 👋

Statamic 4 is due out any day now (in fact the [first beta release](https://github.com/statamic/cms/releases/tag/v4.0.0-beta.1) was tagged yesterday). 

We use this addon in a few of our projects and I was wondering if there was any plans to update this addon soon for compatibility with Statamic 4?

**Comment by joshuanoyes** [comment]
Hi @duncanmcclean 

We've got a PR open for Statamic 4 support (https://github.com/WithCandour/statamic-aardvark-seo/pull/161) and - following a bit more testing - we're aiming for a release early next week :slightly_smiling_face: 

Thanks,

Josh

**Comment by duncanmcclean** [comment]
Awesome! Thanks for updating this issue.

**Comment by mattmultiplied** [comment]
Is there any update on when this will be available?

**Comment by ahartmann-preeco** [comment]
As we had the same issue, we just checked out a specific commit of the dev 3.0 branch like this:

`"withcandour/aardvark-seo": "dev-dev/3.0#5e9644d"`

So far this seems to work until there is an official release that is compatible with Statamic 4.0

**Comment by mattmultiplied** [comment]
> As we had the same issue, we just checked out a specific commit of the dev 3.0 branch like this:
> 
> `"withcandour/aardvark-seo": "dev-dev/3.0#5e9644d"`
> 
> So far this seems to work until there is an official release that is compatible with Statamic 4.0

Awesome, that'll do the job until they get the official release rolled out.

**Comment by joshuanoyes** [comment]
Hi, apologies for the delay in getting the release published - V4 support has just been [released](https://github.com/WithCandour/statamic-aardvark-seo/releases/tag/3.0.0) :slightly_smiling_face: Thanks!
