### ISSUE TITLE
Sitemap not displaying collections.

### ISSUE THREAD

**Issue by geertjanknapen1** [justkidding96/statamic-aardvark-seo#165]
I have a bunch of collections and a bunch of taxonomies. I've excluded every taxonomy from the sitemap, and have NOT excluded any collections. However, when I hit the sitemap route, it's empty. Any reason why? Our project is heavily customized, could that be the issue?

It makes sense that there are no entries for the taxonomies since I've excluded them, but collections should in theory show up.

I also cannot create a taxonomy/collection mapping, since we only attach a taxonomy to an entry, it's not done through the collection. We kind of use taxonomies as a category.
Could that be an issue?

Are there any additional settings that I'm not aware of not listed below?

`<url>/sitemap.xml` result:
<img width="403" alt="image" src="https://github.com/WithCandour/statamic-aardvark-seo/assets/33750300/486978fb-325b-46da-bc91-b558c1d7f6a7">

Sitemap settings:
![image](https://github.com/WithCandour/statamic-aardvark-seo/assets/33750300/348b6a38-af4e-4dd5-a75d-efda9e18c3af)

**Comment by CandourDevs** [comment]
@geertjanknapen1 Sorry for the delay in replying. Unfortunately, we haven’t been able to recreate this. Is it possible that you have set no-index on your collections? That was the only thing we tried that removed the collections from the sitemap.

**Comment by geertjanknapen1** [comment]
Heya, we don't use the no-index on collections. However this issue has been moved to the backburner in January, so I have no way to recreate it now, and no use for it at the moment either. So unless you can do something with this limited information, you might as well close it :)

Thanks for replying though!

**Comment by CandourDevs** [comment]
@geertjanknapen1 Thank you for letting us know. It's much appreciated. We'll close it for now, but obviously, feel free to reopen if it causes you an issue in the future.
