### ISSUE TITLE
Statamic SSG - Call to a member function url() on null

### ISSUE THREAD

**Issue by bradfx** [justkidding96/statamic-aardvark-seo#167]
Running `php please ssg:generate --verbose` with `withcandour/aardvark-seo@3.0.0` and `statamic/cms@4.45.0` and `statamic/ssg@2.2.0` gives me:

```sh
Gathering content to be generated...

   Error

  Call to a member function url() on null

  at vendor/statamic/ssg/src/Request.php:51
     47▕     }
     48▕
     49▕     public function getPathInfo(): string
     50▕     {
  ➜  51▕         return $this->page->url();
     52▕     }
     53▕
     54▕     public function path()
     55▕     {

  1   vendor/symfony/http-foundation/Request.php:1022
      Statamic\StaticSite\Request::getPathInfo()

  2   vendor/laravel/framework/src/Illuminate/Http/Request.php:108
      Symfony\Component\HttpFoundation\Request::getUri()

  3   vendor/withcandour/aardvark-seo/src/Listeners/AppendEntrySeoFieldsListener.php:20
      Illuminate\Http\Request::url()

  4   vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:441
      WithCandour\AardvarkSeo\Listeners\AppendEntrySeoFieldsListener::handle(Object(Statamic\Events\EntryBlueprintFound))
```

Perhaps this is related to https://github.com/statamic/ssg/issues/134 ?

Is anyone at Candour using SSG with Statamic V4?

**Comment by bradfx** [comment]
In statamic v3 I could get around this error sometimes by doing `please stache:warm` but not anymore with v4.

**Comment by bradfx** [comment]
I'm not sure how to help further. I'm not great with PHP. Anything else I can do to help?

**Comment by bradfx** [comment]
@AndrewHaine any thoughts? Thanks bro!

**Comment by bradfx** [comment]
By the way if I `composer remove withcandour/aardvark-seo` the SSG site builds fine. It only fails with the above error when `withcandour/aardvark-seo` is added.

**Comment by CandourDevs** [comment]
@brad-sf Hi. Sorry about your difficulties. We were able to run `php please ssg:generate` on the latest versions of Statamic and Aardvark without a problem. We recommend updating your versions, if you are able, and giving it another try.

**Comment by bradfx** [comment]
Works on latest :)
