### ISSUE TITLE
clearIndexCache too few arguments

### ISSUE THREAD

**Issue by jsblair9** [justkidding96/statamic-aardvark-seo#44]
When `SitemapController::clearCacheByHandle()` calls `self::clearIndexCache()` I'm getting an error that it requires 1 param but 0 passed. 

I temporarily just added a null fallback `clearIndexCache($locale = null)` to resolve for now, but figured I'd make yall aware if anyone else hits the issue!

Running php 7.3.14 locally using valet and on the latest version of the addon.

**Comment by AndrewHaine** [comment]
Hey @jsblair9 ,

Thanks for spotting, just released 1.2.9 which fixes this :)
