### ISSUE TITLE
Error On Deployment

### ISSUE THREAD

**Issue by aerni** [justkidding96/statamic-aardvark-seo#57]
I'm running into this error on deployment:

```log
Unable to prepare route [sitemap_{handle}.xml] for serialization. 
Another route has already been assigned name [aardvark-xml-sitemap]. 
In AbstractRouteCollection.php line 212:
```

I tracked it down to be an issue with `php artisan optimize`. When I remove this command, the deployment runs successfully.

**Comment by AndrewHaine** [comment]
Thanks @aerni ,

Just released a fix for this in 2.0.1, the sitemap routes just needed to be named when they were defined
