### ISSUE TITLE
Error: This action is unauthorized

### ISSUE THREAD

**Issue by aerni** [justkidding96/statamic-aardvark-seo#58]
If you don't give permission to `View General Settings`, your users will be greeted by a `This action is unauthorized` error when clicking on the SEO navigation.

Try with these permissions and see it fail:

```php
- 'configure aardvark settings'
- 'view aardvark marketing settings'
- 'update aardvark marketing settings'
- 'view aardvark social settings'
- 'update aardvark social settings'
- 'view aardvark sitemap settings'
- 'update aardvark sitemap settings'
- 'view aardvark defaults settings'
- 'update aardvark defaults settings'
```

**Comment by AndrewHaine** [comment]
Thanks @aerni ,

Just released a fix for this, we're now looping through all the possible settings and picking the first one which the user has access to, instead of just redirecting to the general settings
