### ISSUE TITLE
SEO fields are saved to blueprint

### ISSUE THREAD

**Issue by aerni** [justkidding96/statamic-aardvark-seo#59]
The SEO section also appears in blueprint builder in the CP. When saving a blueprint, all the SEO fields are saved to file. This might lead to unwanted behavior, as the user now has control over the fields. Also, it might lead to issues with updates.

**Comment by AndrewHaine** [comment]
Thanks @aerni  for the spot on this one,

In the latest release the SEO fields won't get added to the blueprint editor, you may need to remove any SEO fields which were previously saved to a blueprint for this to take effect
