### ISSUE TITLE
Ensure PHP 8 compatibility

### ISSUE THREAD

**Issue by fxkopp** [justkidding96/statamic-aardvark-seo#69]
Upgrading from Version 2.0.2 to 2.06. is not possible using PHP 8 due to a dependency package.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - whitecube/lingua[1.0.0, ..., 1.0.4] require php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - withcandour/aardvark-seo 2.0.6 requires whitecube/lingua ^1.0 -> satisfiable by whitecube/lingua[1.0.0, ..., 1.0.4].
    - Root composer.json requires withcandour/aardvark-seo ^2.0.6 -> satisfiable by withcandour/aardvark-seo[2.0.6].
```

Is there any solution yet?

**Comment by AndrewHaine** [comment]
Hi @fxkopp ,

Thanks for looking at this, i've opened an [issue with the author](https://github.com/whitecube/lingua/issues/5) of that depencency but we may have to look at implementing the functionality that package gives us ourselves if we don't hear back

**Comment by fxkopp** [comment]
Hi @AndrewHaine ,

Thanks for looking into it. Any estimation on when you either gonna replace the package or making it PHP 8 compatible (as the author suggested)?

Currently running Statamic on PHP 8 and it would be nice to be able to upgrade your plugin to the latest version.

**Comment by AndrewHaine** [comment]
Hi @fxkopp ,

We'll be looking into submitting a PR to the original repo within the next couple of weeks, we're quite busy internally at the moment so I will have a chat with our project manager to see when we can get this work scheduled in

**Comment by AndrewHaine** [comment]
Hi @fxkopp ,

The developers of the dependency have updated the package for PHP8 compatibility, updating Aardvark should now be possible :)
