### ISSUE TITLE
[FR] Change assets container

### ISSUE THREAD

**Issue by jeremydouglas** [justkidding96/statamic-aardvark-seo#73]
Aardvark expects an assets container of `assets`. It would be great to have this available in the config to change to a different container.

**Comment by AndrewHaine** [comment]
Hi @jeremydouglas ,

This should already be possible but not sure if it's documented so i'll get it added. Once the addon is installed a `config/aardvark-seo.php` file will be created, in there you will be able to change the asset container used for the SEO image fields.
