### ISSUE TITLE
Commit settings to Git?

### ISSUE THREAD

**Issue by jeremydouglas** [justkidding96/statamic-aardvark-seo#74]
This is more of a question. I expected the Aardvark settings would be committed to Git. Settings for Aardvark are saved in `/storage/statamic/addons/aardvark-seo`. Which, Statamic has ignored from Git by default.

Is it a bad idea to add the settings folder to Git and have settings backed up?

**Comment by aerni** [comment]
Add it to Git if you need to. I do the same. No issue here.

**Comment by AndrewHaine** [comment]
I would agree with @aerni , committing the files in storage should be fine, just be sure to only include `storage/statamic/addons` to prevent logs and other bits being committed

**Comment by mikemartin** [comment]
Took me too long to get this right, so here's my gitignore settings for `/storage/statamic/.gitignore`:
```
/*
!/addons/
!.gitignore
```
