### ISSUE TITLE
Seo fields in collection overview

### ISSUE THREAD

**Issue by HRR1337** [justkidding96/statamic-aardvark-seo#75]
Hi there,

Dont know exactly the place to request an feature, though I thought.. lets do it here.

Would like to see that we can add seo fields in the overview of an collection (just like normal 'fields'). So I can determine which collection or page needs to have an custom meta title or description..

Thanks!

**Comment by jeremydouglas** [comment]
@HRR1337, looks like they moved away from this strategy. See #59.
