### ISSUE TITLE
Github -> settings not stored?

### ISSUE THREAD

**Issue by HRR1337** [justkidding96/statamic-aardvark-seo#76]
Hi there, 

I have an live site and an develop location (local). When I change general settings in live or develop side, it wont push it to github (and therefore dosn't deploy to live or isn't visible in my local dev). 

Is there an way to fix this?

Thanks!

**Comment by devonbeard** [comment]
I also have been having this problem. Just realized the settings don't get saved, so the settings get reverted to defaults on production.

**Comment by devonbeard** [comment]
@HRR1337 There is a closed issue, stating to remove the settings files from the gitignore to be able to save these settings. I tried that and it worked for me. https://github.com/WithCandour/statamic-aardvark-seo/issues/74

**Comment by mikemartin** [comment]
@HRR1337 You could update `/storage/statamic/.gitignore` with:
```
/*
!/addons/
!.gitignore
```

**Comment by bradfx** [comment]
Or just manually track the Aardvark SEO files...
```git
git add storage/statamic/addons/aardvark-seo/* -f
```
```git
Changes to be committed:
	new file:   storage/statamic/addons/aardvark-seo/aardvark_general.yaml
	new file:   storage/statamic/addons/aardvark-seo/aardvark_sitemap.yaml
	new file:   storage/statamic/addons/aardvark-seo/aardvark_social.yaml
```

**Comment by AndrewHaine** [comment]
Closing in favour of proposed solutions, thanks all!

**Comment by ncla** [comment]
This seems like an unexpected behavior for someone who uses the Statamic Git integration. I think default location should be changed or this should be documented.

If mikemartin's .gitignore change still didn't track the storage addons directory, then you can try this one, editing `/storage/statamic/.gitignore`:

```
*
!.gitignore
!addons/
!addons/**/*
```

**Comment by AndrewHaine** [comment]
Thank you for the feedback on this one, confirmed that moving the location of stored Aardvark settings will be changed in the future to ensure that it is accessible for the git integration. This is likely to be in Aardvark v2.1
