### ISSUE TITLE
Sitemap not rendering https

### ISSUE THREAD

**Issue by devonbeard** [justkidding96/statamic-aardvark-seo#85]
Hey Folks, 

I have aardvark generating sitemaps for our site. However, we are getting some mixed urls within it instead of all https. Is there a setting that I can force the sitemap to use https urls? 

https://www.trustworthy.com/sitemap.xml

**Comment by AndrewHaine** [comment]
Hey @devonbeard ,

The sitemap URL should get generated from the current Statamic site, please could you check the value for the site URL in `config/statamic/sites.php` . This may need to be changed to `https://www.trustworthy.com` if it isn't set to that already (you'll also need to clear the application & config caches after updating this value).

**Comment by devonbeard** [comment]
Got it! Thanks 🙏

**Comment by devonbeard** [comment]
@AndrewHaine wanted to follow up here. After, updating the `config/statamic/sites.php` I end up with broken 404 page links. Do you know why that would happen?

**Comment by AndrewHaine** [comment]
Hey @devonbeard , ah that's interesting, I'm not immediately sure why that would happen. Would you be able to send over an example?

**Comment by AdD959** [comment]
Was this issue resolved? I'm having the same problem. Regardless if I set my sites.php url to "/" (recommended) or absolute a https url - the aardvark seo tool is still generating a http sitemap.xml

**Comment by AdD959** [comment]
I've also set URL::forceScheme('https'); in my AppServiceProvider
