### ISSUE TITLE
Issue with emtpy meta description behavior on multiple localizations

### ISSUE THREAD

**Issue by mmai1554** [justkidding96/statamic-aardvark-seo#90]
Hi, 
An issue in multisite: If the meta description field is empty in the current locale it prints out the default locale meta description (if set). I think this is an unwanted behavior. For example: If I write the Meta Description for my German Version page and I do not fill out the field for the English Version, I expect the output for meta description on the English Page the relevant body of the text of the english Page and not the German meta description. A German Meta Description on an English Page does not make sense in my opinion. Or did I miss something?

**Comment by AndrewHaine** [comment]
Hey @mmai1554 ,

Thank you for raising this, looking at a test multisite setup I've got running it seems that Statamic falls back to adding the default locale values to the page context (Aardvark uses the page context for getting on-page values like the meta title/description).

I'll add this to our tasklist and we'll investigate on our end and get a fix in place to enable you to opt-out of this behaviour for Aardvark fields.

Thanks,
Andrew

**Comment by CandourDevs** [comment]
We are closing this, as it is now three years old and we are unable to recreate. Feel free to reopen if it is still a problem.
