### ISSUE TITLE
Allow default {{ fields }} to be linked to metadata or description.

### ISSUE THREAD

**Issue by tao** [justkidding96/statamic-aardvark-seo#98]
I have 28 collections and probably 20 of them have a `synopsis` field already that is a short description of the page. Is it possible to set meta description in the settings to use `{{ synopsis }}` field and fall-back to empty / custom input. Otherwise be able to link synopsis to the meta description in each collection.

At the moment if you add `{{ synopsis }}` to the meta description field then it doesn't show the value in the Google search preview.

**Comment by AndrewHaine** [comment]
Hi @tao ,

Please could you let me know what version of Aardvark you're on and the fieldtype used for the synopsis field? we recently fixed an issue with antlers tags not being parsed inside of the SEO fields, this was released in v2.0.15.

You should be able to set the default value at a collection level by going to`SEO` -> `Content defaults` -> `[collection] defaults` and then adding `{{ synopsis }}` or `{{ synopsis | strip_tags }}` into the meta description box. This will then pull through that field for all entries in the collection but you can still override that value at an entry level.
